# Generated by Django 3.1.5 on 2021-02-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='News Title')),
                ('Discraptions', models.TextField(max_length=700, verbose_name='News Discraptions')),
                ('Image', models.ImageField(max_length=700, upload_to='', verbose_name='News Image')),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News Model',
            },
        ),
    ]
