# Generated by Django 3.1.5 on 2021-02-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodell',
            name='NewsLink',
            field=models.CharField(default='', max_length=255, verbose_name='News Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsmodell',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
