# Generated by Django 3.1.5 on 2021-02-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210225_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodell',
            name='NewsLink',
            field=models.CharField(max_length=1000, verbose_name='News Link'),
        ),
    ]
