# Generated by Django 3.1.5 on 2021-02-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='galleryModell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(max_length=700, upload_to='', verbose_name='News Image')),
            ],
        ),
    ]
