# Generated by Django 3.1.5 on 2021-02-24 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('IsTrack', models.BooleanField(blank=True, default=False, null=True, verbose_name='This is link ? if this is track please put track link above')),
                ('TrackLink', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '2nd Mother Categoreis',
            },
        ),
        migrations.CreateModel(
            name='MotherCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Grand Category Title')),
                ('TitleEnglish', models.CharField(max_length=255, verbose_name='English Grand Category Title')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Let this field empty')),
                ('test', models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link')], default='Category Page', max_length=255)),
            ],
            options={
                'verbose_name_plural': '1st Main Categoreis',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('IsTrack', models.BooleanField(blank=True, default=False, null=True, verbose_name='This is link ? if this is track please put track link above')),
                ('TrackLink', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categoreis.category')),
            ],
            options={
                'verbose_name_plural': '3rd Child Categoreis',
            },
        ),
        migrations.CreateModel(
            name='SubMultiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('TitleEnglish', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='let this field empty')),
                ('IsTrack', models.BooleanField(blank=True, default=False, null=True, verbose_name='This is link ? if this is track please put track link above')),
                ('TrackLink', models.CharField(blank=True, max_length=10000, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categoreis.subcategory')),
            ],
            options={
                'verbose_name_plural': '4th Child Categoreis',
            },
        ),
        migrations.CreateModel(
            name='SoundTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('TrackLink', models.CharField(max_length=10000)),
                ('slugTrack', models.SlugField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tracks', to='categoreis.submulticategory')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categoreis.mothercategory'),
        ),
    ]
