# Generated by Django 3.1.5 on 2021-02-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='TitleEnglish',
            field=models.CharField(default='', max_length=255, verbose_name='English Category Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='TitleEnglish',
            field=models.CharField(default='', max_length=255, verbose_name='English Category Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='IsTrack',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='This is link ? if this is link please write it above'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='TrackLink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='You will definitely write it here'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='children_one', to='categoreis.mothercategory', verbose_name='Category Of'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Let this field empty'),
        ),
        migrations.AlterField(
            model_name='mothercategory',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='mothercategory',
            name='TitleEnglish',
            field=models.CharField(max_length=255, verbose_name='English Category Title'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='IsTrack',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='This is link ? if this is link please write it above'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='TrackLink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='You will definitely write it here'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='children_two', to='categoreis.category', verbose_name='Category Of'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Let this field empty'),
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='IsTrack',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='This is link ? if this is link please write it above'),
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='TitleEnglish',
            field=models.CharField(max_length=255, verbose_name='English Category Title'),
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='TrackLink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='You will definitely write it here'),
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='children_Three', to='categoreis.subcategory', verbose_name='Category Of'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Let this field empty'),
        ),
    ]
