# Generated by Django 3.1.5 on 2021-02-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0002_auto_20210224_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundtrack',
            name='slugTrack',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
