# Generated by Django 3.1.5 on 2021-02-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0003_auto_20210224_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundtrack',
            name='slugTrack',
        ),
        migrations.AddField(
            model_name='soundtrack',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Let this field empty'),
        ),
    ]
