# Generated by Django 3.1.5 on 2021-02-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0004_auto_20210224_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Let this field empty'),
        ),
        migrations.AlterField(
            model_name='mothercategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Let this field empty'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Let this field empty'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Let this field empty'),
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Let this field empty'),
        ),
    ]
