# Generated by Django 3.1.5 on 2021-02-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0008_auto_20210224_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mothercategory',
            name='test',
        ),
        migrations.AddField(
            model_name='category',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
        migrations.AddField(
            model_name='mothercategory',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
        migrations.AddField(
            model_name='soundtrack',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
        migrations.AddField(
            model_name='submulticategory',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
    ]
