# Generated by Django 3.1.5 on 2021-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0010_mothercategory_linkis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mothercategory',
            name='LinkIs',
            field=models.CharField(max_length=1055, verbose_name='Put Fall Link if This is #Book,\n Or This Is YouTube Or Sound Put Link From Src embed'),
        ),
    ]
