# Generated by Django 3.1.5 on 2021-02-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0012_auto_20210224_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='LinkBook',
            field=models.CharField(default='', max_length=1055, verbose_name='Put Fall Link If This is #Book Or Page,\n Or This Is YouTube Or Sound Put Link From Src embed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='LinkEmbed',
            field=models.CharField(default='', max_length=1055, verbose_name='Put Link From Src Embed If This #YouTube Or #Sound '),
            preserve_default=False,
        ),
    ]
