# Generated by Django 3.1.5 on 2021-02-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0013_auto_20210224_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mothercategory',
            name='LinkBook',
        ),
        migrations.RemoveField(
            model_name='mothercategory',
            name='LinkEmbed',
        ),
        migrations.AddField(
            model_name='mothercategory',
            name='LinkIs',
            field=models.CharField(default='', max_length=1055, verbose_name='Put Fall Link Here'),
            preserve_default=False,
        ),
    ]
