# Generated by Django 3.1.5 on 2021-02-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0014_auto_20210225_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='IsTrack',
        ),
        migrations.RemoveField(
            model_name='category',
            name='LinkBook',
        ),
        migrations.RemoveField(
            model_name='category',
            name='LinkEmbed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='TrackLink',
        ),
        migrations.AddField(
            model_name='category',
            name='LinkIs',
            field=models.CharField(blank=True, max_length=1055, null=True, verbose_name='Put Fall Link Here'),
        ),
        migrations.AlterField(
            model_name='mothercategory',
            name='LinkIs',
            field=models.CharField(blank=True, max_length=1055, null=True, verbose_name='Put Fall Link Here'),
        ),
    ]
