# Generated by Django 3.1.5 on 2021-02-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0016_auto_20210225_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='LinkIs',
        ),
        migrations.RemoveField(
            model_name='mothercategory',
            name='LinkIs',
        ),
        migrations.AddField(
            model_name='category',
            name='IsTrack',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='This is link ? if this is link please write it above'),
        ),
        migrations.AddField(
            model_name='category',
            name='LinkBook',
            field=models.CharField(default='', max_length=1055, verbose_name='Put Fall Link If This is #Book Or Page,\n Or This Is YouTube Or Sound Put Link From Src embed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='LinkEmbed',
            field=models.CharField(default='', max_length=1055, verbose_name='Put Link From Src Embed If This #YouTube Or #Sound '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='TrackLink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='You will definitely write it here'),
        ),
        migrations.AddField(
            model_name='mothercategory',
            name='LinkBook',
            field=models.CharField(default='', max_length=1055, verbose_name='Put Fall Link If This is #Book Or Page,\n Or This Is YouTube Or Sound Put Link From Src embed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mothercategory',
            name='LinkEmbed',
            field=models.CharField(default='', max_length=1055, verbose_name='Put Link From Src Embed If This #YouTube Or #Sound '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
        migrations.AlterField(
            model_name='mothercategory',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='Chicese_list',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Page Link', 'Page Link')], default='Category Page', max_length=255, verbose_name='Choice What is it'),
        ),
    ]
