# Generated by Django 3.1.5 on 2021-02-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0018_auto_20210225_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Chicese_list',
        ),
        migrations.RemoveField(
            model_name='category',
            name='IsTrack',
        ),
        migrations.RemoveField(
            model_name='category',
            name='LinkBook',
        ),
        migrations.RemoveField(
            model_name='category',
            name='LinkEmbed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='TrackLink',
        ),
        migrations.RemoveField(
            model_name='mothercategory',
            name='BookLink',
        ),
        migrations.RemoveField(
            model_name='mothercategory',
            name='IsBook',
        ),
        migrations.AddField(
            model_name='category',
            name='BookLink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Put Link Here'),
        ),
        migrations.AddField(
            model_name='category',
            name='IsBook',
            field=models.BooleanField(default=False, max_length=255, verbose_name='This is Book Or Page Link?'),
        ),
    ]
