# Generated by Django 3.1.5 on 2021-02-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0023_auto_20210225_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundtrack',
            name='Chicese_list',
            field=models.CharField(choices=[('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video')], max_length=255, verbose_name='Choice What is it'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Item Title'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='TitleEnglish',
            field=models.CharField(max_length=255, verbose_name='English Item Title'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='TrackLink',
            field=models.CharField(max_length=10000, verbose_name='Item Link'),
        ),
    ]
