# Generated by Django 3.1.5 on 2021-02-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoreis', '0025_soundtrack_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoundTrack',
        ),
    ]
