# Generated by Django 3.1.6 on 2021-02-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorya',
            name='barent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.categorya'),
            preserve_default=False,
        ),
    ]
