# Generated by Django 3.1.6 on 2021-02-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorya_barent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoryA',
            new_name='category',
        ),
    ]
