# Generated by Django 3.1.6 on 2021-02-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210221_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='barent',
        ),
    ]
