# Generated by Django 3.1.6 on 2021-02-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_category_barent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='barent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category'),
        ),
    ]
