# Generated by Django 3.1.6 on 2021-02-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_barent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='barent',
            new_name='parent',
        ),
    ]
