# Generated by Django 3.1.6 on 2021-02-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categorySound',
        ),
    ]
