# Generated by Django 3.1.6 on 2021-02-20 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210221_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='SounTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Category name')),
                ('EnglishName', models.CharField(max_length=50, verbose_name='Category name')),
                ('TrackLink', models.CharField(max_length=50, verbose_name='Book Link (Please Put Fall Download Path)')),
                ('Slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorySounTrack', to='main.categorysound')),
            ],
        ),
    ]
