# Generated by Django 3.1.6 on 2021-02-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sountrack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SounTrack',
            new_name='SoundTrack',
        ),
    ]
