# Generated by Django 3.1.6 on 2021-02-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210221_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysound',
            name='Englishtitle',
            field=models.CharField(default='', max_length=50, verbose_name='Category English Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorysound',
            name='SlugCat',
            field=models.SlugField(blank=True, null=True, verbose_name='let this feild empty'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='EnglishName',
            field=models.CharField(max_length=50, verbose_name='English Track Name'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Track name'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='Slug',
            field=models.SlugField(blank=True, null=True, verbose_name='let this feild empty'),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='TrackLink',
            field=models.CharField(max_length=50, verbose_name='Track Link (Please Put Fall Download Path)'),
        ),
    ]
