# Generated by Django 3.1.5 on 2021-02-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_trackyoutube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysound',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categoryyoutube',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='soundtrack',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trackyoutube',
            name='category',
        ),
        migrations.DeleteModel(
            name='categoryBooks',
        ),
        migrations.DeleteModel(
            name='categorySound',
        ),
        migrations.DeleteModel(
            name='categoryYoutube',
        ),
        migrations.DeleteModel(
            name='SoundTrack',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='TrackYouTube',
        ),
    ]
