# Generated by Django 3.1.5 on 2021-02-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_soundtrack_tracklink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
