# Generated by Django 3.1.5 on 2021-02-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundtrack',
            name='Title',
            field=models.CharField(max_length=1000),
        ),
    ]
