# Generated by Django 3.1.5 on 2021-02-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210222_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundtrack',
            name='Title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='TrackLink',
            field=models.CharField(max_length=1000),
        ),
    ]
