# Generated by Django 3.1.5 on 2021-02-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210222_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundtrack',
            old_name='slug',
            new_name='slugTrack',
        ),
    ]
