# Generated by Django 3.1.5 on 2021-02-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210222_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='submulticategory',
            name='TitleEnglish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='let this field empty'),
        ),
    ]
