# Generated by Django 3.1.5 on 2021-02-22 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_submulticategory_titleenglish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundtrack',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tracks', to='main.submulticategory'),
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='TitleEnglish',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submulticategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='let this field empty'),
        ),
    ]
