# Generated by Django 3.1.5 on 2021-02-22 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210222_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundtrack',
            name='Subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubCategort', to='main.subcategory'),
        ),
    ]
