# Generated by Django 3.1.5 on 2021-02-22 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_soundtrack_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundtrack',
            name='Subcategory',
        ),
    ]
