# Generated by Django 3.1.5 on 2021-02-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_soundtrack_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='submulticategory',
            name='IsTrack',
            field=models.BooleanField(default=True, verbose_name='This is Trck ? '),
        ),
    ]
