# Generated by Django 3.1.5 on 2021-02-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_submulticategory_istrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submulticategory',
            name='IsTrack',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='IsTrack',
            field=models.BooleanField(default=False, verbose_name='This is Trck ? '),
        ),
    ]
