# Generated by Django 3.1.5 on 2021-02-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210222_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='TrackLink',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='IsTrack',
            field=models.BooleanField(default=False, verbose_name='This is link ? if this is track please put track link above'),
        ),
    ]
