# Generated by Django 3.1.5 on 2021-02-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210222_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='IsTrack',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='This is link ? if this is track please put track link above'),
        ),
        migrations.AddField(
            model_name='category',
            name='TrackLink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
