# Generated by Django 3.1.5 on 2021-02-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210223_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mothercategory',
            options={'verbose_name_plural': 'Mother Category Class'},
        ),
        migrations.AddField(
            model_name='mothercategory',
            name='TitleEnglish',
            field=models.CharField(default='', max_length=255, verbose_name='English Grand Category Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mothercategory',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Grand Category Title'),
        ),
        migrations.AlterField(
            model_name='mothercategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Let this field empty'),
        ),
    ]
