# Generated by Django 3.1.5 on 2021-02-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20210223_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='mothercategory',
            name='test',
            field=models.CharField(choices=[('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link'), ('Just Link', 'Just Link')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
