# Generated by Django 3.1.5 on 2021-02-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_mothercategory_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2nd Mother Categoreis'},
        ),
        migrations.AlterModelOptions(
            name='mothercategory',
            options={'verbose_name_plural': '1st Main Categoreis'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '3rd Child Categoreis'},
        ),
        migrations.AlterModelOptions(
            name='submulticategory',
            options={'verbose_name_plural': '4th Child Categoreis'},
        ),
        migrations.AlterField(
            model_name='mothercategory',
            name='test',
            field=models.CharField(choices=[('Category Page', 'Category Page'), ('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video'), ('Book Link', 'Book Link')], default='Category Page', max_length=255),
        ),
    ]
