# Generated by Django 3.1.5 on 2021-02-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210224_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundtrack',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='submulticategory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MotherCategory',
        ),
        migrations.DeleteModel(
            name='SoundTrack',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='SubMultiCategory',
        ),
    ]
