# Generated by Django 3.1.5 on 2021-02-27 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoreis', '0026_delete_soundtrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0044_auto_20210224_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Item Title')),
                ('TitleEnglish', models.CharField(max_length=255, verbose_name='English Item Title')),
                ('Chicese_list', models.CharField(choices=[('Sound Cloud Track', 'Sound Cloud Track'), ('YouTube Video', 'YouTube Video')], max_length=255, verbose_name='Choice What is it')),
                ('TrackLink', models.CharField(max_length=10000, verbose_name='Item Link')),
                ('slugTrack', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Let this field empty')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tracks', to='categoreis.submulticategory')),
                ('likes', models.ManyToManyField(related_name='blogpost_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sounds And Youtube',
            },
        ),
    ]
