# Generated by Django 3.1.5 on 2021-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_soundtrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsModell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chicese_list', models.CharField(choices=[('Facebook Icon', 'Facebook Icon'), ('YouTube Icon', 'YouTube Icon'), ('SoundCloud Icon', 'SoundCloud Icon'), ('Twitter Icon', 'Twitter Icon'), ('Insta Icon', 'Insta Icon'), ('Telegram Icon', 'Telegram Icon')], max_length=255, verbose_name='Choice What is it')),
                ('Name', models.CharField(max_length=255, verbose_name='Icon Title')),
                ('Link', models.CharField(max_length=255, verbose_name='Link Is')),
            ],
            options={
                'verbose_name_plural': 'Social Media Icons',
            },
        ),
    ]
