# Generated by Django 3.1.5 on 2021-03-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_iconsmodell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconsmodell',
            name='Name',
        ),
    ]
