# Generated by Django 3.1.6 on 2021-03-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_iconsmodell_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundtrack',
            name='likes',
        ),
    ]
